AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*

Rails:
  Enabled: true

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: Include, TreatCommentsAsGroupSeparators.
# Include: **/*.gemfile, **/Gemfile, **/gems.rb
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Offense count: 23
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

# FIXME: rails new -> rubocop --auto-correct で消える例外規則
# Offense count: 1
# Configuration parameters: EnforcedStyle.
# SupportedStyles: slashes, arguments
Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

# Offense count: 13
Style/Documentation:
  Enabled: false
